---
title: "Regression excercise"
author: "Byungju Kim"
date: "2018³â 10¿ù 25ÀÏ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

```{r}
 library(MASS)
 library(glmnet)

 set.seed(19875)  # Set seed for reproducibility
 n <- 1000  # Number of observations
 p <- 5000  # Number of predictors included in model
 real_p <- 15 


 set.seed<-1000
 x <- matrix(rnorm(n*p), nrow=n, ncol=p)
 y <- apply(x[,1:real_p], 1, sum) + rnorm(n)

 # Split data into train (2/3) and test (1/3) sets
 train_rows <- sample(1:n, .66*n)
 x.train <- x[train_rows, ]
 x.test <- x[-train_rows, ]

 y.train <- y[train_rows]
 y.test <- y[-train_rows]

 fit.lasso <- glmnet(x.train, y.train, family="gaussian", alpha=1)
 fit.ridge <- glmnet(x.train, y.train, family="gaussian", alpha=0)
 fit.elnet <- glmnet(x.train, y.train, family="gaussian", alpha=.5)
 
 for (i in 0:10) {
    assign(paste("fit", i, sep=""), cv.glmnet(x.train, y.train, type.measure="mse", 
                                              alpha=i/10,family="gaussian"))
 }
 
  # Plot solution paths:
  par(mfrow=c(3,2))
  
  # For plotting options, type '?plot.glmnet' in R console
  plot(fit.lasso, xvar="lambda")
  plot(fit10, main="LASSO")

  plot(fit.ridge, xvar="lambda")
  plot(fit0, main="Ridge")

  plot(fit.elnet, xvar="lambda")
  plot(fit5, main="Elastic Net")
 
 

```
