---
title: "Hardy Weinberg Equation"
author: "BJ Kim"
date: "2017년 5월 16일"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Hardy-Weinberg Principle

Allele and genotype frequency will remained constant from generation to generation if following assumptions are met : 

- Diploid organism.
- Infinite Population.
- Discrete Generation
- Random Mating
- No selection
- No migration
- No mutation
- equal initial genotype frequencies in the two sexes

So, genotype frequencies are expected to combine into genotypes based on the simple laws of probability from allele frequency.

## proof.

**a locus with two alleles A and a**

let one locus of population have two allels, A and a, with the frequenccy of genotype $f(AA)$, $f(Aa)$, $f(aa)$.

1. we can estimate the sum of the genotypes for AA Aa aa is 1.

$$ f(AA) + f(Aa) + f(aa) =1$$
 
2. we also knows the sum of frequency A and a is 1.

$$ p(A) + p(a) = 1$$

3. we can estimate the allele frequency from its genotype frequencies.

$$\begin{align} p(A)=f(AA) + \frac{1}{2} f(Aa) \end{align}$$ 

$$\begin{align} p(a)=f(Aa) + \frac{1}{2} f(aa) \end{align}$$


under the Hardy-Weinberge principle's assumption, we could estimate the genotype frequencies of 2nd generation as followed.

$$\begin{align*} 1 &= (f(AA) + f(Aa) + f(aa))^2 \\ & = f(AA)^2 + f(Aa)^2 + f(aa)^2 + 2f(AA)f(Aa) +2f(AA)f(aa) + 2f(Aa)(aa) \end{align*}$$

here is the 2nd generation

| mating genotypes | mating frequency | expected genotype |
|------------------|------------------|-------------------|
| AA x AA          | $f(AA)^2$        | AA                |
| AA x Aa          | $2 \times f(Aa) * f(AA)$ | $\frac{1}{2} (AA + Aa)$ | 
| AA x aa          | $2 \times f(AA) * f(aa)$ | Aa        | 
| Aa x Aa          | $f(Aa)^2$ | 1/4 AA 1/2 Aa 1/4 aa |
| Aa x aa          | $2 \times f(AA) * f(Aa)$ | 1/2 Aa + 1/2 aa |
| aa x aa          | $f(aa)^2$        | aa                |


from those results, we can estimates the followings

$$\begin{align*} f'(AA) & = f(AA)^2 + \frac{1}{4} \times f(Aa)^2 + 2 \times \frac{1}{2} f(AA)(fAa) \\
 & = (f(AA)+1/2f(Aa))^2 \\ 
 & = p(A)^2 \end{align*}$$


$$\begin{align*} f'(aa) & = f(aa)^2 + \frac{1}{4} \times f(Aa)^2 + 2 \times \frac{1}{2} f(aa)(fAa) \\
 & = (f(aa)+1/2f(Aa))^2 \\ 
 & = p(a)^2 \end{align*}$$


$$\begin{align*} f'(Aa) & = 2\frac{1}{2} f(AA)f(Aa) + 2 \times f(AA)f(aa) + \frac{1}{2} f(Aa)^2 +2 \times \frac{1}{2} f(AA)f(Aa) \end{align*}$$



if the one locus of the population has two alleles denoted A and a with the frequencies $f(A)=p$ and $f(a)=q$, the expected genotype frequencies under random mating are $f(AA)= p^2$ for AA homozygotes and $f(aa)= q^2$ for aa homozyzygotes and $f(Aa)= 2pq$ for the heterozygotes.




1. the allele frequency does not change from one generation to the next, so the gene pool is not evolving at this locus.
2. 

## Equation.


**2 Allele System**

$$AA, Aa, aa : p^2, 2p(1-p) + (1-p)^2$$

**more than 2 alleles**

if we have 3 alleles. hardy weinberg equation is calculated by

$$ (p+q+r)&2 = p2 (AA) + 2pq + q^2 (BB) + 2pr (AC) + wqr(BC) + r^2 (CC) $$

## Problems and critics

- mating is not random which is phisically retained for past hundred of years.
- the timimgeneration of next generation

